# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AmityCreateIdeasApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for AmityCreateIdeasApp
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  
  target 'AmityCreateIdeasAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
